
name: Deploy jet-w.astro-blog default template docs

on:
  push:
    branches:
      # make sure this is the branch you are using
      - main

permissions:
  contents: write

jobs:
  deploy-astro-blog:
    runs-on: ubuntu-latest
    # needs: environment-prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Build Root Package
        run: npm install && npm run build

      - name: Build Blog
        env:
          NODE_OPTIONS: --max_old_space_size=8692
          SITE_URL: https://jet-w.github.io
          BASE_PATH: /jet-w.astro-blog
        run: |-
          cd templates/default && npm install && npm run build

      - name: Add .nojekyll file
        run: touch templates/default/dist/.nojekyll

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Deploy Docs
          branch: gh-pages
          folder: templates/default/dist