
name: Deploy jet-w.astro-blog default template docs

on:
  push:
    branches:
      # make sure this is the branch you are using
      - main

permissions:
  contents: write

jobs:
  deploy-astro-blog:
    runs-on: ubuntu-latest
    # needs: environment-prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Build Blog
        env:
          NODE_OPTIONS: --max_old_space_size=8692
          VUEPRESS_SHIKI_DISABLE: true             # disable shiki for unused languages
        run: |-
          cd templates/default && npm run build

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Deploy Docs
          branch: gh-pages
          folder: templates/default/dist